---
- name: Install Software
  win_chocolatey:
    name: "{{ item }}"
    state: absent
  with_items:
    - firefox
    - lightshot
    - 7zip  
    - zoom
    - skype
    
- name: Touch a file (creates if not present, updates modification time if present)
  win_file:
    path: C:\Temp\foo.conf
    state: touch
